packages:
  # Applications
  - "apps/*"

  # Shared packages
  - "packages/*"

  # Backend services
  - "services/*"

  # Exclude Rust services from pnpm (they use Cargo)
  - "!services/rules-engine"
  - "!services/grid-solver"
  - "!services/shared-rust"
