// Static images hosted in /public/images/
// Generated by: node scripts/download-images.mjs
// Generated on: 2025-12-13T15:26:38.313Z

export const RACE_IMAGES: Record<string, string> = {
  'human': '/images/races/human.png',
  'elf': '/images/races/elf.png',
  'dwarf': '/images/races/dwarf.png',
  'halfling': '/images/races/halfling.png',
  'dragonborn': '/images/races/dragonborn.png',
  'gnome': '/images/races/gnome.png',
  'half-elf': '/images/races/half-elf.png',
  'half-orc': '/images/races/half-orc.png',
  'tiefling': '/images/races/tiefling.png',
};

export const CLASS_IMAGES: Record<string, string> = {
  'barbarian': '/images/classes/barbarian.png',
  'bard': '/images/classes/bard.png',
  'cleric': '/images/classes/cleric.png',
  'druid': '/images/classes/druid.png',
  'fighter': '/images/classes/fighter.png',
  'monk': '/images/classes/monk.png',
  'paladin': '/images/classes/paladin.png',
  'ranger': '/images/classes/ranger.png',
  'rogue': '/images/classes/rogue.png',
  'sorcerer': '/images/classes/sorcerer.png',
  'warlock': '/images/classes/warlock.png',
  'wizard': '/images/classes/wizard.png',
};

export const BACKGROUND_IMAGES: Record<string, string> = {
  'acolyte': '/images/backgrounds/acolyte.png',
  'criminal': '/images/backgrounds/criminal.png',
  'folk-hero': '/images/backgrounds/folk-hero.png',
  'noble': '/images/backgrounds/noble.png',
  'sage': '/images/backgrounds/sage.png',
  'soldier': '/images/backgrounds/soldier.png',
  'hermit': '/images/backgrounds/hermit.png',
  'entertainer': '/images/backgrounds/entertainer.png',
};

export const TERRAIN_IMAGES: Record<string, string> = {
  'stone_floor': '/images/terrain/stone_floor.png',
  'grass': '/images/terrain/grass.png',
  'water': '/images/terrain/water.png',
  'lava': '/images/terrain/lava.png',
  'sand': '/images/terrain/sand.png',
  'snow': '/images/terrain/snow.png',
  'forest': '/images/terrain/forest.png',
  'swamp': '/images/terrain/swamp.png',
};

export const HERO_IMAGES: Record<string, string> = {
  'epic_battle': '/images/heroes/epic_battle.png',
  'dungeon_entrance': '/images/heroes/dungeon_entrance.png',
  'tavern_gathering': '/images/heroes/tavern_gathering.png',
};

export function getRaceImage(raceId: string): string {
  return RACE_IMAGES[raceId] || '';
}

export function getClassImage(classId: string): string {
  return CLASS_IMAGES[classId] || '';
}

export function getBackgroundImage(backgroundId: string): string {
  return BACKGROUND_IMAGES[backgroundId] || '';
}

export function getTerrainImage(terrainId: string): string {
  return TERRAIN_IMAGES[terrainId] || '';
}

export function getHeroImage(heroId: string): string {
  return HERO_IMAGES[heroId] || '';
}
